server {
    listen 8099;
    root /var/log.hdd/babycam;
    autoindex on;
    client_max_body_size 100M;
    
    location / {
        try_files $uri $uri/ =404;
        add_header Access-Control-Allow-Origin *;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
    }
}
