node {
  name = "emqx@127.0.0.1"
  cookie = "emqxsecretcookie"  
  data_dir = "/var/lib/emqx"
}

listeners.tcp.default {
  bind = "0.0.0.0:1883"
  max_connections = 1024000
}

mqtt {
  allow_anonymous = true
}

dashboard {
  listeners.http {
    bind = "0.0.0.0:18083"
  }
  default_username = "admin"
  default_password = "public"
}

log {
  console {
    enable = true
    level = warning
  }
  file {
    default {
      enable = false
    }
  }
}
